#pragma kernel Init
#pragma kernel FillBlack
#pragma kernel DrawSpot
#pragma kernel FillSnow

RWTexture2D<float> snowImage;
float colorValueToAdd;
float resolution;
float xPos;
float yPos;
float spotSize;

int drawOffsetX;
int drawOffsetY;

float fillRate;

[numthreads(8, 8, 1)]
void Init(uint3 id : SV_DispatchThreadID)
{
    snowImage[id.xy] += colorValueToAdd;
}

[numthreads(8, 8, 1)]
void FillBlack(uint3 id : SV_DispatchThreadID)
{
    snowImage[id.xy] = 0.0;
}

[numthreads(8, 8, 1)]
void DrawSpot(uint3 id : SV_DispatchThreadID)
{
    uint2 pixelCoord = uint2(id.x + drawOffsetX, id.y + drawOffsetY);
    if (pixelCoord.x >= (uint)resolution || pixelCoord.y >= (uint)resolution) 
        return;

    float x = (float)pixelCoord.x / resolution;
    float y = (float)pixelCoord.y / resolution;
    
    float dist = distance(float2(x, y), float2(xPos / resolution, yPos / resolution));
    
    if (dist < spotSize)
    {
        float intensity = 1.0 - (dist / spotSize);
        
        if (intensity > snowImage[pixelCoord])
        {
            snowImage[pixelCoord] = intensity;
        }
    }
}

[numthreads(8, 8, 1)]
void FillSnow(uint3 id : SV_DispatchThreadID)
{
    float currentDepth = snowImage[id.xy];
    
    if (currentDepth > 0.0)
    {
        currentDepth -= fillRate;
        snowImage[id.xy] = max(currentDepth, 0.0);
    }
}