#pragma kernel Init
#pragma kernel FillBlack
#pragma kernel DrawSpot
#pragma kernel FillSnow

RWTexture2D<float4> snowImage;
float colorValueToAdd;
float resolution;
float xPos;
float yPos;
float spotSize;

int drawOffsetX;
int drawOffsetY;

float fillRate;

[numthreads(8, 8, 1)]
void Init(uint3 id : SV_DispatchThreadID)
{
    snowImage[id.xy] += float4(colorValueToAdd, colorValueToAdd, colorValueToAdd, 0);
}

[numthreads(8, 8, 1)]
void FillBlack(uint3 id : SV_DispatchThreadID)
{
    snowImage[id.xy] = float4(0.0, 0.0, 0.0, 1.0);
}

[numthreads(8, 8, 1)]
void DrawSpot(uint3 id : SV_DispatchThreadID)
{
    uint2 pixelCoord = uint2(id.x + drawOffsetX, id.y + drawOffsetY);
    if (pixelCoord.x >= (uint)resolution || pixelCoord.y >= (uint)resolution) 
        return;

    float x = (float)pixelCoord.x / resolution;
    float y = (float)pixelCoord.y / resolution;
    
    float dist = distance(float2(x, y), float2(xPos / resolution, yPos / resolution));
    
    if (dist < spotSize)
    {
        float intensity = 1.0 - (dist / spotSize);
        
        if (intensity > snowImage[pixelCoord].x)
        {
            snowImage[pixelCoord] = float4(intensity, intensity, intensity, 1.0);
        }
    }
}

[numthreads(8, 8, 1)]
void FillSnow(uint3 id : SV_DispatchThreadID)
{
    float currentDepth = snowImage[id.xy].x;
    
    if (currentDepth > 0.0)
    {
        currentDepth -= fillRate;
        currentDepth = max(currentDepth, 0.0);
        
        snowImage[id.xy] = float4(currentDepth, currentDepth, currentDepth, 1.0);
    }
}